import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Estimate Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <p className="fixed top-0 z-10 text-tremor-metric text-center font-semibold text-gray-700 p-7 bg-slate-200 w-full">
          Project Time Estimate Calculator
        </p>

        <main className={inter.className}>{children}</main>
      </body>
    </html>
  );
}
